service: serverless-blackbox-backend
frameworkVersion: '3'
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.speedybot_serverless
    events:
      - httpApi:
          path: /
          method: post
  block:
    handler: handler.speedybot_serverless
    events:
      - httpApi:
          path: /api_block
          method: post
  images:
    handler: handler.image_recognition
    events:
      - httpApi:
          path: /image_recognition
          method: post